### ISSUE TITLE
Translation platform down

### ISSUE THREAD

**Issue by comradekingu** [openpetra/openpetra-i18n#1]
@tpokorra 
The translation platform seems to be down
https://wiki.openpetra.org/index.php/Translation_documentation_for_Developers

**Comment by tpokorra** [comment]
Thanks for bringing this up.
I will update the wiki page now.
The translation is now completely different, since we dropped the winforms client, and the javascript client has much less functionality at the moment.
This is the new language file: https://github.com/openpetra/openpetra/blob/master/js-client/locales/en/common.json
We only have a german translation at the moment.
If you want to, you are welcome to provide a pull request directly towards https://github.com/openpetra/openpetra/

Which language would you like to support, or are you in need of?
Do you think, adding another language would help building a community of OpenPetra users?
My issue at the moment is, that we don't have many people working with OpenPetra yet.
